// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSafeStorage } from '@/lib/mobile-utils';

const SUPABASE_URL = "https://kcqppncwydtuuuvkwsoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjcXBwbmN3eWR0dXV1dmt3c29qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjI3MDMsImV4cCI6MjA3NDYzODcwM30.urGNEeCceYcVYhi6AlxFERaA5mXCf_E1uj_R2xyCkd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getSafeStorage(),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});
